type Query {
  phones: [Phone!]!
  phone(id: ID!): Phone
  
  users: [User!]!
  user(id: ID!): User

  orders: [Order!]!
  order(id: ID!): Order
  userOrders(userId: ID!): [Order!]!
  
  catalogs: [Catalog!]!
  catalog(id: ID!): Catalog
  userCatalogs(userId: ID!): [Catalog!]!
  salePhone: Phone
  featuredPhones: [Phone!]!
  newPhones: [Phone!]!
}

type Mutation {
  createPhone(input: PhoneInput!): Phone!
  updatePhone(id: ID!, input: PhoneInput!): Phone!
  deletePhone(id: ID!): Boolean!
  
  updateUser(input: UpdateUserInput!): User!
  deleteUser(id: ID!): Boolean!

  createOrder(input: OrderInput!): Order!
  updateOrderStatus(id: ID!, status: OrderStatus!): Order!
  deleteOrder(id: ID!): Boolean!

  createCatalog(input: CatalogInput!): Catalog!
  updateCatalog(id: ID!, input: CatalogInput!): Catalog!
  deleteCatalog(id: ID!): Boolean!
  addPhoneToCatalog(catalogId: ID!, phoneId: ID!): Catalog!
  removePhoneFromCatalog(catalogId: ID!, phoneId: ID!): Catalog!
}

type Phone {
  id: ID!
  brand: String!
  model: String!
  price: Float!
  description: String!
  seller: User @goField(forceResolver: true)
  createdAt: String!
  updatedAt: String!
}

type User {
  id: ID!
  username: String!
  email: String!
  role: Role!
  phones: [Phone!] @goField(forceResolver: true)
  createdAt: String!
  updatedAt: String!
}

input PhoneInput {
  brand: String!
  model: String!
  price: Float!
  description: String!
}

input UpdateUserInput {
  id: ID!
  username: String
  email: String
  password: String
  role: Role
}

enum Role {
  USER
  ADMIN
}

type Order {
  id: ID!
  user: User!
  phones: [Phone!]!
  status: OrderStatus!
  createdAt: String!
  updatedAt: String!
}

input OrderInput {
  userId: ID!
  phoneIDs: [ID!]!
  shippingAddress: String!
}

enum OrderStatus {
  PENDING
  PROCESSING
  SHIPPED
  DELIVERED
  CANCELLED
}

type Catalog {
  id: ID!
  name: String!
  phones: [Phone!]!
  createdAt: String!
  updatedAt: String!
}

input CatalogInput {
  name: String!
  phoneIDs: [ID!]
}

directive @goField(forceResolver: Boolean, name: String) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION
