type Query {
  phones: [Phone!]! @auth
  phone(id: ID!): Phone @auth
  
  users: [User!]! @auth @admin
  user(id: ID!): User @auth
  me: User! @auth
  myTokens: [Token!]! @auth
}

type Mutation {
  createPhone(input: PhoneInput!): Phone! @auth
  updatePhone(id: ID!, input: PhoneInput!): Phone! @auth
  deletePhone(id: ID!): Boolean! @auth
  
  signup(input: SignupInput!): AuthPayload!
  login(input: LoginInput!): AuthPayload!
  logout: Boolean! @auth
  updateUser(input: UpdateUserInput!): User! @auth
  deleteUser(id: ID!): Boolean! @auth
  updateMe(input: UpdateMeInput!): User! @auth
  deleteMe: Boolean! @auth
  invalidateTokens: Boolean! @auth
}

type Phone {
  id: ID!
  brand: String!
  model: String!
  price: Float!
  description: String!
  seller: User!
  createdAt: String!
  updatedAt: String!
}

type User {
  id: ID!
  username: String!
  email: String!
  role: Role!
  phones: [Phone!]!
  createdAt: String!
  updatedAt: String!
}

type Token {
  id: ID!
  token: String!
  createdAt: String!
  expiresAt: String!
}

type AuthPayload {
  token: String!
  user: User!
}

input PhoneInput {
  brand: String!
  model: String!
  price: Float!
  description: String!
}

input SignupInput {
  username: String!
  email: String!
  password: String!
}

input LoginInput {
  username: String!
  password: String!
}

input UpdateUserInput {
  id: ID!
  username: String
  email: String
  password: String
  role: Role
}

input UpdateMeInput {
  username: String
  email: String
  password: String
}

enum Role {
  USER
  ADMIN
}

directive @auth on FIELD_DEFINITION | FIELD
directive @admin on FIELD_DEFINITION | FIELD
