type Query {
  phones: [Phone!]!
  phone(id: ID!): Phone
  
  users: [User!]!
  user(id: ID!): User
}

type Mutation {
  createPhone(input: PhoneInput!): Phone!
  updatePhone(id: ID!, input: PhoneInput!): Phone!
  deletePhone(id: ID!): Boolean!
  
  updateUser(input: UpdateUserInput!): User!
  deleteUser(id: ID!): Boolean!
}

type Phone {
  id: ID!
  brand: String!
  model: String!
  price: Float!
  description: String!
  seller: User!
  createdAt: String!
  updatedAt: String!
}

type User {
  id: ID!
  username: String!
  email: String!
  role: Role!
  phones: [Phone!]!
  createdAt: String!
  updatedAt: String!
}

input PhoneInput {
  brand: String!
  model: String!
  price: Float!
  description: String!
}

input UpdateUserInput {
  id: ID!
  username: String
  email: String
  password: String
  role: Role
}

enum Role {
  USER
  ADMIN
}
