definitions:
  github_com_is-web-y26_m3302-milovatskiy_internal_domain_general.Phone:
    properties:
      Condition:
        enum:
        - Excellent
        - Good
        - Fair
        - Poor
        type: string
        x-enum-varnames:
        - Excellent
        - Good
        - Fair
        - Poor
      battery:
        type: string
      brand:
        type: string
      camera:
        type: string
      cpu:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      id:
        type: integer
      isUsed:
        type: boolean
      issues:
        type: string
      name:
        type: string
      price:
        type: number
      screenSize:
        type: string
      sellerID:
        type: integer
      storage:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  internal_domain_user.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/internal_domain_user.Role'
      username:
        type: string
    type: object
  internal_domain_user.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  internal_domain_user.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/internal_domain_user.UserResponse'
    type: object
  internal_domain_user.Role:
    enum:
    - user
    - admin
    type: string
    x-enum-varnames:
    - RoleUser
    - RoleAdmin
  internal_domain_user.Token:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      expiresAt:
        type: string
      id:
        type: integer
      token:
        type: string
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
  internal_domain_user.UpdateResponse:
    properties:
      status:
        type: string
    type: object
  internal_domain_user.UpdateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  internal_domain_user.User:
    properties:
      Role:
        enum:
        - user
        - admin
        type: string
        x-enum-varnames:
        - RoleUser
        - RoleAdmin
      cart:
        items:
          $ref: '#/definitions/github_com_is-web-y26_m3302-milovatskiy_internal_domain_general.Phone'
        type: array
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      id:
        type: integer
      lastLogin:
        type: string
      passwordHash:
        type: string
      tokens:
        items:
          $ref: '#/definitions/internal_domain_user.Token'
        type: array
      updatedAt:
        type: string
      username:
        type: string
    type: object
  internal_domain_user.UserResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/phones:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_is-web-y26_m3302-milovatskiy_internal_domain_general.Phone'
            type: array
      security:
      - BearerAuth: []
    post:
      parameters:
      - description: Phone details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_is-web-y26_m3302-milovatskiy_internal_domain_general.Phone'
      responses:
        "201":
          description: Created
      security:
      - BearerAuth: []
  /api/phones/{id}:
    delete:
      parameters:
      - description: Phone ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
    put:
      parameters:
      - description: Phone ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated phone details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_is-web-y26_m3302-milovatskiy_internal_domain_general.Phone'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_is-web-y26_m3302-milovatskiy_internal_domain_general.Phone'
      security:
      - BearerAuth: []
  /api/users:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_domain_user.UserResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
    post:
      parameters:
      - description: User data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_domain_user.CreateUserRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_domain_user.UserResponse'
  /api/users/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid user ID
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
    put:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User update data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_domain_user.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_domain_user.UserResponse'
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
  /api/users/login:
    post:
      parameters:
      - description: Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_domain_user.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_domain_user.LoginResponse'
  /api/users/logout:
    post:
      responses: {}
      security:
      - BearerAuth: []
  /api/users/me:
    delete:
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_domain_user.UserResponse'
      security:
      - BearerAuth: []
    put:
      parameters:
      - description: Update data
        in: body
        name: request
        schema:
          $ref: '#/definitions/internal_domain_user.UpdateUserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_domain_user.UpdateResponse'
      security:
      - BearerAuth: []
swagger: "2.0"
