package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/general"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/graph/generated"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/graph/model"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/user"
)

// CreatePhone is the resolver for the createPhone field.
func (r *mutationResolver) CreatePhone(ctx context.Context, input model.PhoneInput) (*model.Phone, error) {
	userID := ctx.Value("user_id").(uint)

	phone := &general.Phone{
		Brand:       input.Brand,
		Price:       input.Price,
		Description: input.Description,
		SellerID:    userID,
	}

	if err := r.PhoneService.CreatePhone(phone); err != nil {
		return nil, err
	}

	return &model.Phone{
		ID:          strconv.FormatUint(uint64(phone.ID), 10),
		Brand:       phone.Brand,
		Price:       phone.Price,
		Description: phone.Description,
	}, nil
}

// UpdatePhone is the resolver for the updatePhone field.
func (r *mutationResolver) UpdatePhone(ctx context.Context, id string, input model.PhoneInput) (*model.Phone, error) {
	userID := ctx.Value("user_id").(uint)
	isAdmin, _ := ctx.Value("is_admin").(bool)

	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	existingPhone, err := r.PhoneService.GetPhoneByID(uint(phoneID))
	if err != nil {
		return nil, err
	}

	if existingPhone.SellerID != userID && !isAdmin {
		return nil, fmt.Errorf("unauthorized")
	}

	phone := &general.Phone{
		Brand:       input.Brand,
		Price:       input.Price,
		Description: input.Description,
		SellerID:    existingPhone.SellerID,
	}

	if err := r.PhoneService.UpdatePhone(phone); err != nil {
		return nil, err
	}

	return &model.Phone{
		ID:          id,
		Brand:       phone.Brand,
		Price:       phone.Price,
		Description: phone.Description,
	}, nil
}

// DeletePhone is the resolver for the deletePhone field.
func (r *mutationResolver) DeletePhone(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	isAdmin, _ := ctx.Value("is_admin").(bool)

	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return false, err
	}

	phone, err := r.PhoneService.GetPhoneByID(uint(phoneID))
	if err != nil {
		return false, err
	}

	if phone.SellerID != userID && !isAdmin {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.PhoneService.DeletePhone(uint(phoneID)); err != nil {
		return false, err
	}

	return true, nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignupInput) (*model.AuthPayload, error) {
	hashedPassword, err := user.HashPassword(input.Password)
	if err != nil {
		return nil, err
	}

	user := &user.User{
		Username:     input.Username,
		Email:        input.Email,
		PasswordHash: hashedPassword,
		Role:         user.RoleUser,
	}

	if err := r.UserService.CreateUser(user); err != nil {
		return nil, err
	}

	token, err := r.UserService.GenerateJWT(user)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:       strconv.FormatUint(uint64(user.ID), 10),
			Username: user.Username,
			Email:    user.Email,
			Role:     model.Role(user.Role),
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	req := user.LoginRequest{
		Username: input.Username,
		Password: input.Password,
	}

	user, err := r.UserService.Login(req)
	if err != nil {
		return nil, err
	}

	token, err := r.UserService.GenerateJWT(user)
	if err != nil {
		return nil, err
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:       strconv.FormatUint(uint64(user.ID), 10),
			Username: user.Username,
			Email:    user.Email,
			Role:     model.Role(user.Role),
		},
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	token := ctx.Value("token").(string)
	if err := r.UserService.InvalidateToken(token); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	userID := ctx.Value("user_id").(uint)
	isAdmin, _ := ctx.Value("is_admin").(bool)

	id, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, err
	}

	if userID != uint(id) && !isAdmin {
		return nil, fmt.Errorf("unauthorized")
	}

	var role user.Role
	switch *input.Role {
	case model.RoleAdmin:
		role = user.RoleAdmin
	case model.RoleUser:
		role = user.RoleUser
	}

	u := &user.User{
		Username: *input.Username,
		Email:    *input.Email,
		Role:     role,
	}

	if *input.Password != "" {
		hashedPassword, err := user.HashPassword(*input.Password)
		if err != nil {
			return nil, err
		}
		u.PasswordHash = hashedPassword
	}

	if err := r.UserService.UpdateUser(u); err != nil {
		return nil, err
	}

	return &model.User{
		ID:       input.ID,
		Username: u.Username,
		Email:    u.Email,
		Role:     model.Role(u.Role),
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	isAdmin, _ := ctx.Value("is_admin").(bool)

	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return false, err
	}

	if userID != uint(uid) && !isAdmin {
		return false, fmt.Errorf("unauthorized")
	}

	if err := r.UserService.DeleteUser(uint(uid)); err != nil {
		return false, err
	}

	return true, nil
}

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input model.UpdateMeInput) (*model.User, error) {
	userID := ctx.Value("user_id").(uint)

	u, err := r.UserService.GetUserByID(userID)
	if err != nil {
		return nil, err
	}

	if *input.Username != "" {
		u.Username = *input.Username
	}
	if *input.Email != "" {
		u.Email = *input.Email
	}
	if *input.Password != "" {
		hashedPassword, err := user.HashPassword(*input.Password)
		if err != nil {
			return nil, err
		}
		u.PasswordHash = hashedPassword
	}

	if err := r.UserService.UpdateUser(u); err != nil {
		return nil, err
	}

	return &model.User{
		ID:       strconv.FormatUint(uint64(u.ID), 10),
		Username: u.Username,
		Email:    u.Email,
		Role:     model.Role(u.Role),
	}, nil
}

// DeleteMe is the resolver for the deleteMe field.
func (r *mutationResolver) DeleteMe(ctx context.Context) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	if err := r.UserService.DeleteUser(userID); err != nil {
		return false, err
	}
	return true, nil
}

// InvalidateTokens is the resolver for the invalidateTokens field.
func (r *mutationResolver) InvalidateTokens(ctx context.Context) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	if err := r.UserService.InvalidateAllUserTokens(userID); err != nil {
		return false, err
	}
	return true, nil
}

// Phones is the resolver for the phones field.
func (r *queryResolver) Phones(ctx context.Context) ([]*model.Phone, error) {
	userID := ctx.Value("user_id").(uint)
	isAdmin, _ := ctx.Value("is_admin").(bool)

	phones, err := r.PhoneService.FindAllPhones()
	if err != nil {
		return nil, err
	}

	var result []*model.Phone
	for _, phone := range phones {
		if phone.SellerID == userID || isAdmin {
			result = append(result, &model.Phone{
				ID:          strconv.FormatUint(uint64(phone.ID), 10),
				Brand:       phone.Brand,
				Price:       phone.Price,
				Description: phone.Description,
			})
		}
	}

	return result, nil
}

// Phone is the resolver for the phone field.
func (r *queryResolver) Phone(ctx context.Context, id string) (*model.Phone, error) {
	userID := ctx.Value("user_id").(uint)
	isAdmin, _ := ctx.Value("is_admin").(bool)

	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	phone, err := r.PhoneService.GetPhoneByID(uint(phoneID))
	if err != nil {
		return nil, err
	}

	if phone.SellerID != userID && !isAdmin {
		return nil, fmt.Errorf("unauthorized")
	}

	return &model.Phone{
		ID:          id,
		Brand:       phone.Brand,
		Price:       phone.Price,
		Description: phone.Description,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	isAdmin, _ := ctx.Value("is_admin").(bool)
	if !isAdmin {
		return nil, fmt.Errorf("unauthorized")
	}

	users, err := r.UserService.GetAllUsers()
	if err != nil {
		return nil, err
	}

	var result []*model.User
	for _, user := range users {
		result = append(result, &model.User{
			ID:       strconv.FormatUint(uint64(user.ID), 10),
			Username: user.Username,
			Email:    user.Email,
			Role:     model.Role(user.Role),
		})
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID := ctx.Value("user_id").(uint)
	isAdmin, _ := ctx.Value("is_admin").(bool)

	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	if userID != uint(uid) && !isAdmin {
		return nil, fmt.Errorf("unauthorized")
	}

	user, err := r.UserService.GetUserByID(uint(uid))
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:       id,
		Username: user.Username,
		Email:    user.Email,
		Role:     model.Role(user.Role),
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID := ctx.Value("user_id").(uint)
	user, err := r.UserService.GetUserByID(userID)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:       strconv.FormatUint(uint64(user.ID), 10),
		Username: user.Username,
		Email:    user.Email,
		Role:     model.Role(user.Role),
	}, nil
}

// MyTokens is the resolver for the myTokens field.
func (r *queryResolver) MyTokens(ctx context.Context) ([]*model.Token, error) {
	userID := ctx.Value("user_id").(uint)
	tokens, err := r.UserService.GetUserTokens(userID)
	if err != nil {
		return nil, err
	}

	var result []*model.Token
	for _, token := range tokens {
		result = append(result, &model.Token{
			ID:        strconv.FormatUint(uint64(token.ID), 10),
			Token:     token.Token,
			CreatedAt: token.CreatedAt.Format(time.RFC3339),
			ExpiresAt: token.ExpiresAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
