package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"strconv"
	"time"

	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/cart"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/general"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/graph/generated"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/graph/model"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/user"
	"gorm.io/gorm"
)

// CreatePhone is the resolver for the createPhone field.
func (r *mutationResolver) CreatePhone(ctx context.Context, input model.PhoneInput) (*model.Phone, error) {
	phone := &general.Phone{
		Brand:       input.Brand,
		Name:        input.Model,
		Price:       input.Price,
		Description: input.Description,
	}

	if err := r.PhoneService.CreatePhone(phone); err != nil {
		return nil, err
	}

	return &model.Phone{
		ID:          strconv.FormatUint(uint64(phone.ID), 10),
		Brand:       phone.Brand,
		Model:       phone.Name,
		Price:       phone.Price,
		Description: phone.Description,
	}, nil
}

// UpdatePhone is the resolver for the updatePhone field.
func (r *mutationResolver) UpdatePhone(ctx context.Context, id string, input model.PhoneInput) (*model.Phone, error) {
	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	existingPhone, err := r.PhoneService.GetPhoneByID(uint(phoneID))
	if err != nil {
		return nil, err
	}

	phone := &general.Phone{
		Model: gorm.Model{
			ID: existingPhone.ID,
		},
		Brand:       input.Brand,
		Name:        input.Model,
		Price:       input.Price,
		Description: input.Description,
		SellerID:    existingPhone.SellerID,
	}

	if err := r.PhoneService.UpdatePhone(phone); err != nil {
		return nil, err
	}

	seller, err := r.UserService.GetUserByID(phone.SellerID)
	if err != nil {
		return nil, err
	}

	return &model.Phone{
		ID:          id,
		Brand:       phone.Brand,
		Model:       phone.Name,
		Price:       phone.Price,
		Description: phone.Description,
		Seller: &model.User{
			ID:       strconv.FormatUint(uint64(seller.ID), 10),
			Username: seller.Username,
			Email:    seller.Email,
			Role:     model.Role(seller.Role),
		},
	}, nil
}

// DeletePhone is the resolver for the deletePhone field.
func (r *mutationResolver) DeletePhone(ctx context.Context, id string) (bool, error) {
	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return false, err
	}

	if err := r.PhoneService.DeletePhone(uint(phoneID)); err != nil {
		return false, err
	}

	return true, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	userID, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, err
	}

	existingUser, err := r.UserService.GetUserByID(uint(userID))
	if err != nil {
		return nil, err
	}

	var role user.Role
	if input.Role != nil {
		switch *input.Role {
		case model.RoleAdmin:
			role = user.RoleAdmin
		case model.RoleUser:
			role = user.RoleUser
		}
	} else {
		role = existingUser.Role
	}

	username := existingUser.Username
	if input.Username != nil {
		username = *input.Username
	}

	email := existingUser.Email
	if input.Email != nil {
		email = *input.Email
	}

	u := &user.User{
		Model: gorm.Model{
			ID: existingUser.ID,
		},
		Username:     username,
		Email:        email,
		Role:         role,
		PasswordHash: existingUser.PasswordHash,
	}

	if input.Password != nil && *input.Password != "" {
		hashedPassword, err := user.HashPassword(*input.Password)
		if err != nil {
			return nil, err
		}
		u.PasswordHash = hashedPassword
	}

	if err := r.UserService.UpdateUser(u); err != nil {
		return nil, err
	}

	phones, err := r.PhoneService.FindAllPhones()
	if err != nil {
		return nil, err
	}

	var phoneModels []*model.Phone
	for _, phone := range phones {
		if phone.ID != u.ID {
			continue
		}

		phoneModels = append(phoneModels, &model.Phone{
			ID:          strconv.FormatUint(uint64(phone.ID), 10),
			Brand:       phone.Brand,
			Model:       phone.Name,
			Price:       phone.Price,
			Description: phone.Description,
		})
	}

	return &model.User{
		ID:        input.ID,
		Username:  u.Username,
		Email:     u.Email,
		Role:      model.Role(u.Role),
		Phones:    phoneModels,
		UpdatedAt: time.Now().Format(time.RFC3339),
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return false, err
	}

	if err := r.UserService.DeleteUser(uint(uid)); err != nil {
		return false, err
	}

	return true, nil
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.OrderInput) (*model.Order, error) {
	userID, err := strconv.ParseUint(input.UserID, 10, 32)
	if err != nil {
		return nil, err
	}

	var phoneIDs []uint
	for _, pid := range input.PhoneIDs {
		id, err := strconv.ParseUint(pid, 10, 32)
		if err != nil {
			return nil, err
		}
		phoneIDs = append(phoneIDs, uint(id))
	}

	order, err := r.CartService.PlaceOrder(uint(userID), phoneIDs)
	if err != nil {
		return nil, err
	}
	return convertToModelOrder(order), nil
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status model.OrderStatus) (*model.Order, error) {
	orderID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, err
	}

	order, err := r.CartService.GetOrderByID(uint(orderID))
	if err != nil {
		return nil, err
	}

	order.Status = cart.OrderStatus(status)

	updatedOrder, err := r.CartService.UpdateOrder(&order)
	if err != nil {
		return nil, err
	}
	return convertToModelOrder(&updatedOrder), nil
}

// DeleteOrder is the resolver for the deleteOrder field.
func (r *mutationResolver) DeleteOrder(ctx context.Context, id string) (bool, error) {
	orderID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return false, err
	}

	err = r.CartService.DeleteOrder(uint(orderID))
	if err != nil {
		return false, err
	}
	return true, nil
}

// Seller is the resolver for the seller field.
func (r *phoneResolver) Seller(ctx context.Context, obj *model.Phone) (*model.User, error) {
	if obj.Seller != nil {
		return obj.Seller, nil
	}

	phoneID, err := strconv.ParseUint(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}

	phone, err := r.PhoneService.GetPhoneByID(uint(phoneID))
	if err != nil {
		return nil, err
	}

	if phone.SellerID == 0 {
		return nil, nil
	}

	user, err := r.UserService.GetUserByID(phone.SellerID)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:       strconv.FormatUint(uint64(user.ID), 10),
		Username: user.Username,
		Email:    user.Email,
		Role:     model.Role(user.Role),
	}, nil
}

// Phones is the resolver for the phones field.
func (r *queryResolver) Phones(ctx context.Context) ([]*model.Phone, error) {
	phones, err := r.PhoneService.FindAllPhones()
	if err != nil {
		return nil, err
	}

	var result []*model.Phone
	for _, phone := range phones {
		var seller *model.User
		if phone.SellerID != 0 {
			user, err := r.UserService.GetUserByID(phone.SellerID)
			if err != nil {
				return nil, err
			}
			seller = &model.User{
				ID:       strconv.FormatUint(uint64(user.ID), 10),
				Username: user.Username,
				Email:    user.Email,
				Role:     model.Role(user.Role),
			}
		}

		result = append(result, &model.Phone{
			ID:          strconv.FormatUint(uint64(phone.ID), 10),
			Brand:       phone.Brand,
			Model:       phone.Name,
			Price:       phone.Price,
			Description: phone.Description,
			Seller:      seller,
		})
	}

	return result, nil
}

// Phone is the resolver for the phone field.
func (r *queryResolver) Phone(ctx context.Context, id string) (*model.Phone, error) {
	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	phone, err := r.PhoneService.GetPhoneByID(uint(phoneID))
	if err != nil {
		return nil, err
	}

	var seller *model.User
	if phone.SellerID != 0 {
		user, err := r.UserService.GetUserByID(phone.SellerID)
		if err != nil {
			return nil, err
		}
		seller = &model.User{
			ID:       strconv.FormatUint(uint64(user.ID), 10),
			Username: user.Username,
			Email:    user.Email,
			Role:     model.Role(user.Role),
		}
	}

	return &model.Phone{
		ID:          id,
		Brand:       phone.Brand,
		Model:       phone.Name,
		Price:       phone.Price,
		Description: phone.Description,
		Seller:      seller,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.GetAllUsers()
	if err != nil {
		return nil, err
	}

	var result []*model.User
	for _, user := range users {
		phones, err := r.PhoneService.FindAllPhones()
		if err != nil {
			return nil, err
		}

		var phoneModels []*model.Phone
		for _, phone := range phones {
			if phone.ID != user.ID {
				continue
			}

			phoneModels = append(phoneModels, &model.Phone{
				ID:          strconv.FormatUint(uint64(phone.ID), 10),
				Brand:       phone.Brand,
				Model:       phone.Name,
				Price:       phone.Price,
				Description: phone.Description,
			})
		}

		result = append(result, &model.User{
			ID:       strconv.FormatUint(uint64(user.ID), 10),
			Username: user.Username,
			Email:    user.Email,
			Role:     model.Role(user.Role),
			Phones:   phoneModels,
		})
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	user, err := r.UserService.GetUserByID(uint(uid))
	if err != nil {
		return nil, err
	}

	phones, err := r.PhoneService.FindAllPhones()
	if err != nil {
		return nil, err
	}

	var phoneModels []*model.Phone
	for _, phone := range phones {
		if phone.ID != user.ID {
			continue
		}

		phoneModels = append(phoneModels, &model.Phone{
			ID:          strconv.FormatUint(uint64(phone.ID), 10),
			Brand:       phone.Brand,
			Model:       phone.Name,
			Price:       phone.Price,
			Description: phone.Description,
		})
	}

	return &model.User{
		ID:       id,
		Username: user.Username,
		Email:    user.Email,
		Role:     model.Role(user.Role),
		Phones:   phoneModels,
	}, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {
	orders, err := r.CartService.GetAllOrders()
	if err != nil {
		return nil, err
	}

	var result []*model.Order
	for i := range orders {
		result = append(result, convertToModelOrder(&orders[i]))
	}
	return result, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	orderID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, err
	}

	order, err := r.CartService.GetOrderByID(uint(orderID))
	if err != nil {
		return nil, err
	}
	return convertToModelOrder(&order), nil
}

// UserOrders is the resolver for the userOrders field.
func (r *queryResolver) UserOrders(ctx context.Context, userID string) ([]*model.Order, error) {
	uid, err := strconv.ParseUint(userID, 10, 32)
	if err != nil {
		return nil, err
	}

	orders, err := r.CartService.GetOrdersByUserID(uint(uid))
	if err != nil {
		return nil, err
	}

	var result []*model.Order
	for i := range orders {
		result = append(result, convertToModelOrder(&orders[i]))
	}
	return result, nil
}

// Phones is the resolver for the phones field.
func (r *userResolver) Phones(ctx context.Context, obj *model.User) ([]*model.Phone, error) {
	if len(obj.Phones) > 0 {
		return obj.Phones, nil
	}

	userID, err := strconv.ParseUint(obj.ID, 10, 64)
	if err != nil {
		return nil, err
	}

	phones, err := r.PhoneService.FindAllPhones()
	if err != nil {
		return nil, err
	}

	var result []*model.Phone
	for _, phone := range phones {
		if phone.ID != uint(userID) {
			continue
		}

		result = append(result, &model.Phone{
			ID:          strconv.FormatUint(uint64(phone.ID), 10),
			Brand:       phone.Brand,
			Model:       phone.Name,
			Price:       phone.Price,
			Description: phone.Description,
		})
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Phone returns generated.PhoneResolver implementation.
func (r *Resolver) Phone() generated.PhoneResolver { return &phoneResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	phoneResolver    struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)
