package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"strconv"

	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/general"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/graph/generated"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/graph/model"
	"github.com/is-web-y26/m3302-milovatskiy/internal/domain/user"
)

// CreatePhone is the resolver for the createPhone field.
func (r *mutationResolver) CreatePhone(ctx context.Context, input model.PhoneInput) (*model.Phone, error) {
	phone := &general.Phone{
		Brand:       input.Brand,
		Price:       input.Price,
		Description: input.Description,
	}

	if err := r.PhoneService.CreatePhone(phone); err != nil {
		return nil, err
	}

	return &model.Phone{
		ID:          strconv.FormatUint(uint64(phone.ID), 10),
		Brand:       phone.Brand,
		Price:       phone.Price,
		Description: phone.Description,
	}, nil
}

// UpdatePhone is the resolver for the updatePhone field.
func (r *mutationResolver) UpdatePhone(ctx context.Context, id string, input model.PhoneInput) (*model.Phone, error) {
	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	existingPhone, err := r.PhoneService.GetPhoneByID(uint(phoneID))
	if err != nil {
		return nil, err
	}

	phone := &general.Phone{
		Brand:       input.Brand,
		Price:       input.Price,
		Description: input.Description,
		SellerID:    existingPhone.SellerID,
	}

	if err := r.PhoneService.UpdatePhone(phone); err != nil {
		return nil, err
	}

	return &model.Phone{
		ID:          id,
		Brand:       phone.Brand,
		Price:       phone.Price,
		Description: phone.Description,
	}, nil
}

// DeletePhone is the resolver for the deletePhone field.
func (r *mutationResolver) DeletePhone(ctx context.Context, id string) (bool, error) {
	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return false, err
	}

	if err := r.PhoneService.DeletePhone(uint(phoneID)); err != nil {
		return false, err
	}

	return true, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	var role user.Role
	switch *input.Role {
	case model.RoleAdmin:
		role = user.RoleAdmin
	case model.RoleUser:
		role = user.RoleUser
	}

	u := &user.User{
		Username: *input.Username,
		Email:    *input.Email,
		Role:     role,
	}

	if *input.Password != "" {
		hashedPassword, err := user.HashPassword(*input.Password)
		if err != nil {
			return nil, err
		}
		u.PasswordHash = hashedPassword
	}

	if err := r.UserService.UpdateUser(u); err != nil {
		return nil, err
	}

	return &model.User{
		ID:       input.ID,
		Username: u.Username,
		Email:    u.Email,
		Role:     model.Role(u.Role),
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return false, err
	}

	if err := r.UserService.DeleteUser(uint(uid)); err != nil {
		return false, err
	}

	return true, nil
}

// Phones is the resolver for the phones field.
func (r *queryResolver) Phones(ctx context.Context) ([]*model.Phone, error) {
	phones, err := r.PhoneService.FindAllPhones()
	if err != nil {
		return nil, err
	}

	var result []*model.Phone
	for _, phone := range phones {
		result = append(result, &model.Phone{
			ID:          strconv.FormatUint(uint64(phone.ID), 10),
			Brand:       phone.Brand,
			Price:       phone.Price,
			Description: phone.Description,
		})
	}

	return result, nil
}

// Phone is the resolver for the phone field.
func (r *queryResolver) Phone(ctx context.Context, id string) (*model.Phone, error) {
	phoneID, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	phone, err := r.PhoneService.GetPhoneByID(uint(phoneID))
	if err != nil {
		return nil, err
	}

	return &model.Phone{
		ID:          id,
		Brand:       phone.Brand,
		Price:       phone.Price,
		Description: phone.Description,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.GetAllUsers()
	if err != nil {
		return nil, err
	}

	var result []*model.User
	for _, user := range users {
		result = append(result, &model.User{
			ID:       strconv.FormatUint(uint64(user.ID), 10),
			Username: user.Username,
			Email:    user.Email,
			Role:     model.Role(user.Role),
		})
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	uid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}

	user, err := r.UserService.GetUserByID(uint(uid))
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:       id,
		Username: user.Username,
		Email:    user.Email,
		Role:     model.Role(user.Role),
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
